### ISSUE TITLE
Camel and Banana ADD

### ISSUE THREAD

**Issue by ddninja** [ddninja/Camel-and-Banana-Puzzle#1]
Hello World...

**Comment by joy98** [comment]
vector<vector<int>> adj_rev;

vector<bool> winning;
vector<bool> losing;
vector<bool> visited;
vector<int> degree;

void dfs(int v) {
    visited[v] = true;
    for (int u : adj_rev[v]) {
        if (!visited[u]) {
            if (losing[v])
                winning[u] = true;
            else if (--degree[u] == 0)
                losing[u] = true;
            else
                continue;
            dfs(u);
        }
    }
}
